title       = "alternativeme"
baseURL     = "https://alternativeme-cli.tamnd.com/"
description = "A command line for alternativeme."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/alternativeme-cli"
